eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6001/eureka/
  instance:
    prefer-ip-address: true #使用ip注册到eureka服务列表
server:
  port: 7001
spring:
  application:
    name: plat-service
